version: "3.9"

services:
  clonebot:
    image: ghcr.io/missemily2022/clonebot:new
    container_name: clonebot
    environment:
      - telegram_token=5029929958:AAHu0IVElgBWGWN96eQ37znCSOGPN-1NhR4
      - user_ids=1048800271
      - group_ids=-1
      - PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped
